name: CogentDesi
favicon: null
layout_spectrum: 0.6879699
typography_spectrum: 0.265014321077615
title: CogentDesi
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#3F48CC'
  brandStrength: 0.5053706
  lightness: 0.7086367132142186
  saturation: 0.02177366032265127
  rhythmicContrast: 0.8004106511361897
purpose: []
